---
title: Clean Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: Write your site description here. It will be used as your sites meta
  description as well!
baseurl: "/startbootstrap-clean-blog-jekyll"
url: http://yourdomain.com
twitter_username: SBootstrap
github_username: davidtmiller
facebook_username: IronSummitMedia
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
